# PostgreSQL with High Availability in Docker
# https://hub.docker.com/_/postgres
#
version: '3.1'
services:
  db.master:
    image: db.master
    networks:
    - net_postgres
    volumes:
    - vol_postgres:/var/lib/postgresql/data
    environment:
    - POSTGRES_USER=devops
    - POSTGRES_PASSWORD=devops
    - POSTGRES_DB=postgres
    - PG_MASTER_REP_USER=devops_rep
    - PG_MASTER_REP_PASS=devops_rep
    restart: always
    build:
      context: ./db/
      args:
      - mode=master

  db.standby:
    image: db.standby
    networks:
    - net_postgres
    volumes:
    - vol_postgres:/var/lib/postgresql/data
    environment:
    - PG_MASTER_HOST=db.master
    - PG_MASTER_PORT=5432
    - PG_MASTER_REP_USER=devops_rep
    - PG_MASTER_REP_PASS=devops_rep
    restart: always
    build:
      context: ./db/
      args:
      - mode=standby
    depends_on:
    - db.master

volumes:
  vol_postgres:

networks:
  net_postgres:
